---
title: "SQL to pandas"
output: html_document
---

<br>

With help from the pandas [documentation](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html)

<br>

### Postgres set-up

```{r chunck1}
library(DBI)
library(RPostgres)
library(jsonlite)

# Database connection
config <- jsonlite::read_json('C:/Users/brent/Documents/VS_Code/postgres/postgres/config.json')

con <- DBI::dbConnect(
  RPostgres::Postgres(),
  host      = 'localhost',
  port      = '5432',
  dbname    = 'mlbench_data',
  user      = 'postgres',
  password  = config$pg_password
)
```

```{r chunck2}
# Tips data to r dataframe
qry <- dbSendQuery(conn = con, statement = "select * from data.tips")
rtips <- dbFetch(qry)
head(rtips)
```

<br>

```{sql connection=con}
select * from data.tips limit 10;
```

<br>

### Python set-up

```{r chunck3}
library('reticulate')
use_condaenv(condaenv = 'STOCK_MASTER', required = TRUE)
```

<br>

```{python }
import pandas as pd
ptips = r.rtips
ptips
```

#### N largest tips by sex where total bill > X

```{sql connection=con}
select * from (
	select 
	t.* 
	,row_number() over (partition by sex order by tip) as row_num
	from data.tips t
	where total_bill > 8
) t1
where row_num <= 4

```

```{python }
(
    ptips
    .assign(row_num = ptips.query("total_bill > 8").sort_values(["tip"]).groupby(["sex"]).cumcount() + 1)
    .query("row_num <= 4")
    .sort_values(["sex", "row_num"])
)
```





df['days_lookback'] = df.sort_values(['date'], ascending=False)\
             .groupby(['ticker'])\
             .cumcount() + 1
---------
df['example_2'] = df.sort_values(['date', 'period'], \
             ascending=[False, True])\
             .groupby(['ticker', 'exchange'])\
             .cumcount() + 1