---
title: "Reference Library"
output: 
  html_document:
    toc: FALSE
---


This website is a collection of Python and R notebooks that forms a reference for variance data analysis, modelling and machine learning tasks.  

The site is an addendum to my [blog](https://brentmorrison.netlify.app/).  

Topics are arranged via the menu at the top of the page.  The aim is to have a number of implementations of each topic across language / framework.

<br>

## Update procedures  

If the structure of the site has been altered, i.e., either the ```_site.yml``` or ```_navbar.yml``` have been changed, the ```Build Website``` command must be run.  This rebuilds every .Rmd file with no caching.  

If only a single ```.Rmd``` has been changed then that can be knitted in isolation. 

<br>

## Jupyter notebooks

Some content is constructed using Jupyter notebooks.  This requires conversion to html using the ```nbconvert``` utility shown below.

Example conversion, ipynb to html:  

<br>
```jupyter nbconvert --to html numpyro_models.ipynb```  
<br>

This command will produce a html file called ```numpyro_models.html```.  This file is then copied to the base folder of the site repository before rendering.